a = input('Digite algo: ')
print('O tipo primitivo desse valor é', type (a))
print('Só tem espaços ', a.isspace())
print('é um número ', a.isnumeric())
print('é alfabetico ', a.isalpha())
print('é alfanumerico ', a.isalnum())
print('Esta em maiúsculas ', a.isupper())
print('Esta em minusculas ', a.islower())
print('Esta capitalizada ', a.istitle())